train_file: ./data/tsd_train_trial.csv
dev_file: ./data/tsd_trial.csv
test_files:
  - ./data/tsd_test_spans.csv
  - ./data/tsd_train.csv
  - ./data/tsd_trial.csv
max_length: 192
max_epochs: 5
save_dir: "/content/drive/My Drive/ToxicSpans/results/fixed/rnnsl_tsd_train_trial/"
