type: intersection
files:
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/spanbert_spans/spanbert_spans_best_3_ckpts/preds-3500/spans-pred-original_test.txt"
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/spanbert_spans/spanbert_spans_best_3_ckpts/preds-2000/spans-pred-original_test.txt"
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/spanbert_spans/spanbert_spans_best_3_ckpts/preds-5000/spans-pred-original_test.txt"
path: "/content/drive/My Drive/ToxicSpans/results/fixed/combine_predictions/spans-pred_original_test-intersection_spanbert_spans_best_3_ckpts.txt"
