name: toxic_spans_spans
# model_checkpoint_name: xlm-roberta-large
# model_checkpoint_name: bert-base-multilingual-uncased
# model_checkpoint_name: bigscience/bloom-560m
# model_checkpoint_name: csebuetnlp/banglishbert

# model_checkpoint_name: microsoft/deberta-v3-large
# model_checkpoint_name: microsoft/deberta-v3-base
# model_checkpoint_name: csebuetnlp/banglabert
# model_checkpoint_name: csebuetnlp/banglabert_large
model_checkpoint_name: csebuetnlp/banglabert
# model_checkpoint_name:  xlm-roberta-base
# model_checkpoint_name: sagorsarker/bangla-bert-base

# model_checkpoint_name: sberbank-ai/mGPT
train_files:
  train: ./data/vasha23/train.csv # ./data/tsd_train.csv
  validation: ./data/vasha23/valid.csv # ./data/tsd_trial.csv

  # train: ./data/vasha23_fullfold1/train.csv # ./data/tsd_train.csv
  # validation: ./data/vasha23_fullfold1/valid.csv # ./data/tsd_trial.csv
eval_files:
  test: ./data/vasha23/test_tsd.csv # ./data/tsd_test.csv
tokenizer_params:
  truncation: "only_second"
  max_length: 384
  stride: 128
  return_overflowing_tokens: true
  return_offsets_mapping: true
  padding: max_length
