model_name: autotoken
# model_id: banglabert_10ep
# model_id: debertav3large
model_id: sagorbert
results_dir: ./results/fixed/bert_token/${model_id}
dataset:
  batch_size: 32
  name: toxic_spans_tokens
  # model_checkpoint_name: ${results_dir}/final_model
  # model_checkpoint_name: ${results_dir}/ckpts/checkpoint-15000
  model_checkpoint_name: ${results_dir}/ckpts/checkpoint-4500
  train_files:
    train: ./data/vasha23/train.csv #./data/tsd_train.csv
    validation: ./data/vasha23/valid.csv # ./data/tsd_trial.csv
    # original_test: ./data/tsd_test_spans.csv
  eval_files:
    test: ./data/vasha23/test_tsd.csv # ./data/tsd_test.csv
  label_cls: true
  cls_threshold: 0.3 # can be tuned
  token_threshold: 0.0 # can be tuned
  tokenizer_params:
    truncation: true
    max_length: 384 # originally we used 200
    padding: max_length
    return_offsets_mapping: true
pretrained_args:
  pretrained_model_name_or_path: ${dataset.model_checkpoint_name}
# with_ground: false # true
with_ground: true
save_dir: ${results_dir}/preds/
