'''
# Prothom alo corpus: https://www.kaggle.com/datasets/furcifer/bangla-newspaper-dataset

# সমোচ্চারিত শব্দ: find exhaustive list and deterministic replace
# pdf tesseract ocr

pdf: https://drive.google.com/file/d/1HUz9_MnS3rY7iarnpXffaqvd8TUK5pUc/view
extraction: converstion to word file, or use [OCR](https://github.com/tesseract-ocr/tesseract)

## মুখ্য vs মূর্খ
তিনি ছিলেন জাপান সাম্রাজ্যের অন্যতম মুখ্য ডানপন্থী জাতীয়তাবাদী রাজনৈতিক তত্ত্বদাতা।
ওইটুকু একটা $মুখ্য$ গেঁয়ো মেয়ে।

## গাঁ vs গা
আলহামদুলিল্লাহ$,$অসংখ্য ধন্যবাদ আপনাকে$$ $,$ অনেকটা সময় মনে $হইছিল$ 
  আমি পাহাড়ের উপর $গাঁ$ লাগিয়ে চলছি অবিরাম$,$! $কি$ অদ্ভূত অনুভব$ $! 
  তবে মনের অজান্তেই একটি প্রশ্নের উদয় হলো খাবারগুলো কি হালাল$ $? আমি মুসলিম তাই জানতে 

## পরে vs পড়ে
কিন্তু ওরা দেখতে পায় খেতে পায় না$$ তারা অনেক কষ্ট পায়$$ তাদের দেশের কথা মনে $পরে$ $জায়$।


# Split: error corpus, or prefix suffix
এই $১২ টি$ সিট নিয়েই তিনি প্রধানমন্ত্রী হলেন।

# Merge: deterministically merge
সে রিস্ক আমি নিতে $চাইনা$।

# Punctuation: remove, add, replace
এমন কড়া শাসন কেন$।$
উম্মতও $কোন$ গোত্র নয়$$ এখানে শুধু বহু কাতার হওয়ার কথা $বুঝানো$ হয়েছে।

বিজ্ঞান$$ মনস্কতা ও প্রযুক্তি নিয়ে সহজাত আগ্রহ লক্ষণীয়।

# Transliteration/Foreign Words: api use transliterate/common english words in bangla
# Learn english words in bangla

https://pypi.org/project/google-transliteration-api/

আসলে এলিজাবেথ, আমার $প্রাকটিস$ শেষ করে তোমার সাথে কথা বলতে চাই।
$কন্টাকটরের$ ডাকই বলে $দিল$ এটা তালতলা।
আমিও $সেম$ উত্তর ধরে রেখেছি কিন্তু ক্যামেরার সামনে হয়তো মাথায় আসতো না$$
তিনি $ইংরাজী$ ছাড়াও ইতিহাস, সংস্কৃত ও দর্শনশাস্ত্রে অধ্যাপনা করেছেন।
এরপর $গাই'স$ হাসপাতালে চিকিৎসাশাস্ত্রে ডিগ্রি লাভ করেন।
 
সে রিস্ক আমি নিতে $চাইনা$।
আমরা যখন $বীচে$ গেলাম$,$ আমাদের এসে বলল, ওদিকে যাওয়া যাবে না, ওটা ফরেইন টুরিস্টদের জন্য।

সে $প্রতিউত্তরে$ $বললো$, এটা আল্লাহর $নবীর$ সুন্নাত।
$রাসূল$ করীম $সল্লাল্লাহু$ আলাইহি ওয়াসাল্লাম [...]


## Dialect
কার এতো $টেকা$ $পড়ছে$  যে লাখ টাকা দিয়ে আইফোন $কিনব$ [...]
তুই আমার $লগে$ $নখরা$ $কর$স$$ কপিলা?
শ্রাবণ প্রকাশনীর সামনে $হেতিরা$ $আমাগো$ লগে ছবি তুললো $মাগার$ $টেহা$ দিল না।

## Sadhu Cholito: determinitc list
না, $তাঁহারা$ $চলিয়া$ গেছেন।
বিহারী $কহিল$, না, আমি সত্যই $বলিয়াছি$, তোমাকে আমি বিবাহ $করিব$।

কেবলমাত্র এইটুকু দেখিলেই $হইবে$ যে, অজ্ঞ $লোকদিগের$ কুসংস্কার যেন প্রশ্রয় না পায়।

## Named Entity Problem
কেউ $ব্রাজর্স$ কে খবর দাও$$

## Grammar: Common Mistakes in bangla from grammar
$শুধুমাত্র$ এই স্টেশন এবং ব্যাং ফেই স্টেশন অনন্য।


data_generation standard
1. correct sentence: from a clean corpus, input to data generation: prothom-alo
2. gt: annoted error sentence with $ $
3. sentence: error sentence without dollar
4. correct_pos, tok paris: position (in sentence) and corrected tokens for the error tokens

# Propose suggestion for by using mask language modeling
# Take top-k from the suggestion generated by the model



'''
