model_name: autospans
name: bert
n_steps: 50
type: spans
sample_index: 50 # should be in [0,1999] for test

out_dir: "/content/drive/My Drive/ToxicSpans/results/fixed/IG/spanbert_spans"
word_out_file: ${out_dir}/${sample_index}/word_importances
token_out_file: ${out_dir}/${sample_index}/token_importances
viz_out_file: ${out_dir}/${sample_index}/viz.html
ground_truths_file: ./data/tsd_test_spans.csv
results_dir: "/content/drive/My Drive/ToxicSpans/ToxicSpans/results/fixed/spanbert_spans"
thresh_file: ${results_dir}/preds/thresh.txt
data_config:
  name: toxic_spans_spans
  model_checkpoint_name: ${results_dir}/ckpts/checkpoint-3500
  train_files:
    validation: ./data/tsd_trial.csv
  eval_files:
    test: ./data/tsd_test.csv
  label_cls: true
  cls_threshold: 0.3 # can be tuned
  token_threshold: 0.0 # can be tuned
  tokenizer_params:
    truncation: "only_second"
    max_length: 384
    stride: 128
    return_overflowing_tokens: true
    return_offsets_mapping: true
    padding: max_length
pretrained_args:
  pretrained_model_name_or_path: ${data_config.model_checkpoint_name}
predictions_file: ${results_dir}/preds/spans-pred-original_test.txt
