type: intersection
files:
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/combine_predictions/spans-pred_original_test-union_roberta_token_best_3_ckpts.txt"
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/spanbert_spans/spanbert_spans_best_3_ckpts/preds-3500/spans-pred-original_test.txt"
path: "/content/drive/MyDrive/ToxicSpans/results/fixed/combine_predictions/spans-pred_original_test-intersection_spanbert_spans_union_roberta_token_best_3_ckpts.txt"
