type: intersection
files:
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/combine_predictions/spans-pred_original_test-union_spanbert_spans_best_3_ckpts.txt"
  - "/content/drive/MyDrive/ToxicSpans/results/fixed/roberta_token/roberta_token_best_3_ckpts/preds-1500/spans-pred_original_test.txt"
path: "/content/drive/MyDrive/ToxicSpans/results/fixed/combine_predictions/spans-pred_original_test-intersection_roberta_token_union_spanbert_spans_best_3_ckpts.txt"
