# type: intersection
type: union
base_dir: ""
files:
  # - "../data/pred/spans_pred_bn_large.txt"
  # - "../data/pred/spans_pred_xlm_base.txt"
  # - "../data/pred/spans-pred_test_bn_base.txt"
  # - "../data/pred/spans_pred_debertav3_large.txt"
  - "../data/pred/bertcrf/spans-pred-test_checkpoint-3000.txt"
  - "../data/pred/bertlargecrf/spans-pred-test_checkpoint-3000.txt"

# path: "../data/pred/spans_pred_bnl_xlmb_bnb_dv3l_int.txt"
path: "../data/pred/spans_pred_bertcrf3000_bertlargecrf3000_union.txt"
